version: '3.9'

services :
  mongodb:
    container_name: mern-mongodb
    image: mongo:latest 
    restart: unless-stopped
    command : mongod --oplogSize 512 --timeStampFormat iso8601-local --bind_ip_all --wiredTigerCacheSizeGB 64 
    #environment :
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: root
      #MONGO_INITDB_DATABASE: mern  
    env_file: docker.env
    ports:
      - "27017:27017"
    volumes:
      - ./db/mongo/data:/data/db
      - ./db/mongo/init:/docker-entrypoint-initdb.d:ro
      #- volume_container:/data/db
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD --quiet | grep 1
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "8m"
        max-file: "10"

#volumes:
#  volume_container

